### ISSUE TITLE
Consider relicensing to MIT/BSD

### ISSUE THREAD

**Issue by afonari** [orex/supercell#11]
MIT/BSD is more permissive.

**Comment by orex** [comment]
I don't have any reason to change the license (at least now). Probably, you can consider to use another software (https://github.com/msg-byu/enumlib, for example). For detailed comparison (can be obsolete), see https://jcheminf.springeropen.com/articles/10.1186/s13321-016-0129-3#Sec14

**Comment by afonari** [comment]
Thanks for a fast reply.
