### ISSUE TITLE
Taking too long time for 1961256 no of total combinations

### ISSUE THREAD

**Issue by dwaipayanroni** [orex/supercell#12]
I am trying sampling out lowest 50 Coulomb energy structures from a cif file, where total no of the combination is 1961256 (As printed at the end of a dry run). But it is taking too long time and as the time progresses the no of configuration finished, stored are increasing as well as the no of configuration left is also increasing. How is it possible? Is there any error? And how can I estimate the time remaining to finish this calculation?

Also, I have archived the output files but the Coulomb_energy.txt file is huge alone. How can I handle that?

**Comment by orex** [comment]
Dear dwaipayanroni,

Thank you for your report. Please, fill the form below. It will be much easy for me to help you having the information.

1) Operation system
2) Precompiled or source code installation
3) Did you try a provided examples, if not try Ca2Al2SiO7 step-by-step as described in tutorial https://orex.github.io/supercell/doc/supercell_tutorial.pdf 
4) Exact command you use to run the case.

I expect the normal maximum running time for your configuration about 2-3 minutes or so on modern processors with enough memory. Please, have a look to table 1 in https://jcheminf.springeropen.com/articles/10.1186/s13321-016-0129-3 and table 1 in tutorial https://orex.github.io/supercell/doc/supercell_tutorial.pdf. There you can get an approximate time for some examples. You can run them and compare the times. If you will achieve a significant difference in your machine, most probably you have a technical problems in your system.

**Comment by dwaipayanroni** [comment]
Dear orex,

Thank you for your quick reply. Here is the information in order to your form.
1. Operation System: LINUX. I am running it in a cluster with 62 nodes and 992 cores. Probably the code is running in the master node.

2. I am using the precompiled binary for LINUX system.

3. I have not tried the example. According to the table 1 of the tutorial.pdf the run time for 2x2x3 supercell of FeSbO4, for which the total no of config is 2704156, is 7.5s/7 days. Does it mean it can take any time between this range?

4. The exact command I used : 
../../../Softwares/supercell/supercell -i EntryWithCollCode_test.cif -s 1x1x1 -v 2 -q -n l50 -o out/cell_test -a system_cell_test.zip

Another thing is instead of creating the zip file inside the out folder is has been created outside of the out folder

In my system, there are two partially occupied site with partial occupancy 

Group 2 (24 atomic positions in supercell):
  * Site #1: Li1 (occ. 0.417) -> distributed over 10 positions out of 24 (actual occ.: 0.417).
  Number of combinations for the group is 1961256

Group 3 (96 atomic positions in supercell):
  * Site #1: Li2 (occ. 0.479) -> distributed over 46 positions out of 96 (actual occ.: 0.479).
  Number of combinations for the group is 9223372036854775807

All other sites are fully occupied.

At the end this is printed:

Minimal distance between atoms of two distinct groups: 0.806122 A.

-------------------------------------------------
The total number of combinations is -1961256

**Comment by orex** [comment]
Thank you for the reply! 
In your case the total number of combination is not 1961256, but "-1961256". This value comes from integer overflow when multiplying 1961256 by 9223372036854775807. Supercell program cannot work with such huge number of permutations (see program limitation in the supercell paper https://jcheminf.springeropen.com/articles/10.1186/s13321-016-0129-3 or in the supercell manual https://orex.github.io/supercell/doc/supercell_man.html#section_7). Also the value "Minimal distance between atoms of two distinct groups: 0.806122 A." looks very suspicious for me. Probably you have a structure problems. I suggest to verify the structure with VESTA, for example.

As for "7.5s/7 days" timing, please refer to corresponding section in the tutorial. A meaning of the data is clearly explained there.

Kirill.

**Comment by dwaipayanroni** [comment]
Thank you!

Ok, I understood the problem. Can you please suggest me any other code for my system?

**Comment by orex** [comment]
As far as I know a single, ready to use program is not exists. (see https://jcheminf.springeropen.com/articles/10.1186/s13321-016-0129-3#Sec14 for comparison of existing solutions).

Probably you can find useful an “Symmetry imposed” approach, which I've described in 

Okhotnikov, K. (2016). Comment on “Symmetry and random sampling of symmetry independent configurations for the simulation of disordered solids”, https://arxiv.org/pdf/1606.08062.pdf. 
For most of the systems, I'm working with the lowest electrostatic energy configurations are symmetric. 

I can also suggest to you to check papers

M. Dieb, T., Ju, S., Yoshizoe, K., Hou, Z., Shiomi, J., & Tsuda, K. (2017). MDTS: automatic complex materials design using Monte Carlo tree search. Science and Technology of Advanced Materials, 18(1), 498–503. https://www.tandfonline.com/doi/full/10.1080/14686996.2017.1344083 
where special Monte Carlo algorithm is described.
and paper
Hong, S. U., Singh, S. P., Pyo, M., Park, W. B., & Sohn, K.-S. (2017). Density functional theory calculations for the band gap and formation energy of Pr4−xCaxSi12O3+xN18−x; a highly disordered compound with low symmetry and a large cell size. Phys. Chem. Chem. Phys., 19(25), 16702–16712 http://pubs.rsc.org/en/Content/ArticleLanding/2017/CP/C7CP03247A
where authors uses a genetic algorithm to find a series of configuration with minimal energy.

You can also try to implement by yourself some Metropolis like algorithm.

**Comment by dwaipayanroni** [comment]
Thank you for your suggestions.

**Comment by orex** [comment]
Your are welcome! I appreciate a short feedback about the methods you will choose.

**Comment by dwaipayanroni** [comment]
Sure!
