### ISSUE TITLE
An error in repeating the example of "ice-Ih-adv"

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [orex/supercell#16]
Dear professor,
      I've repeated the example of "**ice-Ih-adv**" , but I found there are a lot of structures in the "ice-Ih-cfgs-final" file. However, in your tutorial, it writes 

> "The process gives only 9 structures which obey both conditions, and which may be found in the ice-Ih-cfgs-final/ directory. "

     I assume that the "**Checking H-H distance**" process do not works well here. If so, I would love to hear your kind suggestion with these problems. 
     It should be mentioned that I added two lines in your **df_cfg.bash**, which I renamed **t2.bash**.

```
module load node/11.1.0
export PRG_GULP=/public1/soft/node/11.1.0/bin/gulp
```
    
   All the materials are in the attachments. Thanks for your kind attention and look forward your reply.
   Best regards,
Jiang Lu 
  
[ice-Ih-adv.zip](https://github.com/orex/supercell/files/2584367/ice-Ih-adv.zip)

**Comment by orex** [comment]
Please, send me the g.out file generated by the script.

**Comment by Jiang-Lu-CAS** [comment]
>           Please, send me the g.out file generated by the script.

Is it the g.out in the "ice-Ih-cfgs-l1" file?
It writes as follows:
[16:15:04] Local gulp not found in ~/public/supercell/supercell-master/data/examples/ice-Ih-adv/ice-Ih-cfgs-l1/ice-Ih-l1_i0328_w2/gulp
[16:15:04] Try running: npm install gulp

Is it means that the gulp is ineffective in the calculation? If so, which part should I change?


[ice-Ih-l1_i0001_w2.zip](https://github.com/orex/supercell/files/2584430/ice-Ih-l1_i0001_w2.zip)

**Comment by orex** [comment]
Dear Jiang-Lu-CAS,
It looks that you use a wrong gulp program. Please, check again my tutorial. There you can find a description and proper link to GULP program. The program you are using now related not to material science, but Javascript testing framework.

**Comment by Jiang-Lu-CAS** [comment]
>           Dear Jiang-Lu-CAS,
> It looks that you use a wrong gulp program. Please, check again my tutorial. There you can find a description and proper link to GULP program. The program you are using now related not to material science, but Javascript testing framework.

Sorry, I will try again. Thank you so much.
