### ISSUE TITLE
An error about the occupancy

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [orex/supercell#17]
Dear Kirill,
     Here is a occupancy difference between my original model and the gained models. In my original model, the occupancy of P1a is 0.167, after the supercell process, the occupancy is 0. What's more, the occupancy of P4a is 0.278, which changed to 0.333 after the supercell process.
     The sn3p4-adv.cif is in attachment, which is gained from sn3p4.cif with specific P atoms grouped and all the atoms fixed. 

`supercell -i sn3p4.cif -p "*:fixed" -o sn3p4-adv.cif `

Then all the 8 P atoms in a sphere were grouped as a-f for sn3p4-adv.cif

    Next, type
`supercell -d -i sn3p4-adv.cif ` 

   There is an error, although it is not reported in the process.

> Group 1 (1 atomic positions in supercell):
>   * Site #1: P1a (occ. 0.167) -> FIXED with occupancy 0.000.
> Group 19 (3 atomic positions in supercell):
>   * Site #1: P4a (occ. 0.278) -> distributed over 1 positions out of 3 (actual occ.: 0.333).
   
 Hoping for your early reply.
 Best wishes,
Jane

[sn3p4.zip](https://github.com/orex/supercell/files/2688743/sn3p4.zip)

**Comment by orex** [comment]
Dear Jiang-Lu-CAS,

I don't see any error of my program in the process, you described. Can you please explain me little more what the error is?

Best,
Kirill.

**Comment by Jiang-Lu-CAS** [comment]
[example+figure.zip](https://github.com/orex/supercell/files/2689278/example%2Bfigure.zip)
>           Dear Jiang-Lu-CAS,
> I don't see any error of my program in the process, you described. Can you please explain me little more what the error is?
> Best,
> Kirill.

Yes, there is no error report in this process. However, the previous P1 and P2 in Sn3P4.cif were ignored in the process, which occupied 0.167 turns out to be 0. An example was shown in attachment, where two P was ignored in the supercell process.

I don't know why the initial P atoms with 0.167 occupancy were missed in the process.

**Comment by Jiang-Lu-CAS** [comment]
But it can not be neglected in this work. What should I do if I want to make the P1a occupied after the supercell process?  change the code of supercell or change the cif ?

**Comment by orex** [comment]
The parameter ` -p "P1a:p=1"` set P1a atom label occupancy to 1. I strongly suggest you to check manual https://orex.github.io/supercell/doc/supercell_man.pdf (-p command) and tutorial sections https://orex.github.io/supercell/doc/supercell_tutorial.pdf "α-SixGe1-xO2 system", "Cu2ZnSnSxSe4-x system" and "piezoelectric ceramics PbZrxTi1-xO3 (PZT)"
P.S. The command takes time. Please, be patience.
