### ISSUE TITLE
ERROR output in example Ca2Al2SiO7

### ISSUE THREAD

**Issue by hlyang1992** [orex/supercell#24]
I run supercell using file(https://github.com/orex/supercell/blob/master/data/examples/Ca2Al2SiO7/Ca2Al2SiO7.cif) with command:

```
supercell -d -i Ca2Al2SiO7.cif -m
```

However, I got error output,

**ERROR: Label AlT2 belong to 2 or more groups.**

**Comment by orex** [comment]
Hello!
Please fill the form below:
1) The version of OS your are using: Windows, MacOS or Linux.
2) Which supercell code? Compiled from site or self-compiled.
3) Full output of supercell program.

**Comment by orex** [comment]
Closed due to inactivity.
