### ISSUE TITLE
Error with non-integer oxidation state

### ISSUE THREAD

**Issue by JacobDing** [orex/supercell#25]
Dear developers, 
I'm trying to model a structure with chemical formula of Cu58S32, however it seems that I can not use a non-integer oxidation state (Cu +1.1, S -2). The error was
```bash
Create atoms population error:
Change supercell size
Switch off charge balancing
Check manual population settings
```
Then I tried the oxidation state of (Cu +1, S -2) and switch off charge balancing. The new problem is 
```bash
ERROR: Electrostatic energy cannot be calculated without charge balancing.
```
If I switch on charge balancing, the formula will be adjusted to Cu64S32.
How can I deal with this structure?

Thank you!
[Cu58S32.txt](https://github.com/orex/supercell/files/3748921/Cu58S32.txt)

**Comment by orex** [comment]
Dear JacobDing,
I'm not sure I have fully understood your problem. But It looks like, that you have to specify Cu charge more precisely `(32*(-2)+58*x=0). x = 1.10344827586206896552`
`supercell -d -i Cu58S32.cif -p "Cu*:c=1.10344827586206896552" -m -q -s 2x2x2`
Sincerely yours,
Kirill.

**Comment by JacobDing** [comment]
Thank you Kirill, the problem is solved with a more precise Cu charge.

**Comment by orex** [comment]
Welcome!
