### ISSUE TITLE
the coulomb_energy for all stucture is zero.

### ISSUE THREAD

**Issue by Caixinzhang-hnu** [orex/supercell#30]
Fm_il00.cif	0.000 eV
Fm_il01.cif	0.000 eV
Fm_il02.cif	0.000 eV
Fm_il03.cif	0.000 eV
Fm_il04.cif	0.000 eV
Fm_il05.cif	0.000 eV
...........
The command line: ./supercell -i NaYF4-P63m.cif  -s 1x1x2  -q -n l20 -o Fm
the oxidation state of elements as I show below:
“_atom_type_symbol
_atom_type_oxidation_number
F1-	-1
Na1+	1
Y3+	3”

**Comment by orex** [comment]
Dear Caixinzhang-hnu,
Please attach the cif file and full output from the supercell program to screen.
Best,
Kirill

**Comment by Caixinzhang-hnu** [comment]
thanks! I get the right value with ‘./supercell -i NaYF4-P6.cif -s 1x1x2 -p "Na*:c=+1" -p "F*:c=-1" -p "Y*:c=+3" -q -n l20 -o P6’.发自我的华为手机-------- 原始邮件 --------发件人： orex <notifications@github.com>日期： 2020年5月12日周二 晚上8:20收件人： orex/supercell <supercell@noreply.github.com>抄送： Caixinzhang-hnu <759602389@qq.com>, Author <author@noreply.github.com>主    题： Re: [orex/supercell] the coulomb_energy for all stucture is zero. (#30)
Dear Caixinzhang-hnu,
Please attach the cif file and full output from the supercell program to screen.
Best,
Kirill

**Comment by orex** [comment]
Good!
