### ISSUE TITLE
Example-PbSnTe-SQS stops without any error

### ISSUE THREAD

**Issue by redmack** [orex/supercell#32]
I am a new supercell user. When I run the example **PbSnTe-SQS** with df.cfg.bash script the program runs but after few seconds it got stuck without any errors. 
The program requires gulp. I have it installed it and the other examples (like ice-Ih) which also requires gulp runs perfectly.

OS:Ubuntu 20.04 LTS
Gulp: 5.2
Supercell version: Latest (installed with the following commands)
git clone --recursive https://github.com/orex/supercell.git && cd supercell && mkdir build && cd build && cmake ../ && make && sudo make install)

![Screenshot from 2020-07-22 10-40-54](https://user-images.githubusercontent.com/68602943/88157063-90d77500-cc0a-11ea-87a4-b609e26db5a4.jpg)
![Screenshot from 2020-07-22 10-39-58](https://user-images.githubusercontent.com/68602943/88157788-7baf1600-cc0b-11ea-987f-174dd162262a.png)

The path shows the gulp executable.

**Comment by orex** [comment]
Please confirm that Ca2Al2SiO7 example is working (first section in the tutorial) and than run the script above with command `bash -x ./df_cfg.bash`

**Comment by redmack** [comment]
The Ca2Al2SiO7 examples works perfectly. Then ran the PbSnTe-SQS example using you `bash -x ./df_cfg.bash` command. The results seem the same. 

the gulp just stops calculation after a certain time. Like it should create 4 inputs according to **rcuts** value but in that process it just stops in the middle of the first step. 

![Screenshot from 2020-07-22 11-33-04](https://user-images.githubusercontent.com/68602943/88162467-af8d3a00-cc11-11ea-803b-6186311baa28.png)
![Screenshot from 2020-07-22 11-33-32](https://user-images.githubusercontent.com/68602943/88162470-b025d080-cc11-11ea-89ca-c1bf4229a2fc.png)
![Screenshot from 2020-07-22 11-37-38](https://user-images.githubusercontent.com/68602943/88162472-b025d080-cc11-11ea-845f-2a6a6cb1231d.jpg)
![Screenshot from 2020-07-22 11-39-21](https://user-images.githubusercontent.com/68602943/88162477-b0be6700-cc11-11ea-8b83-658e205de3ec.png)
![Screenshot from 2020-07-22 11-48-13](https://user-images.githubusercontent.com/68602943/88162678-ee22f480-cc11-11ea-867b-a011181f2465.png)

**Comment by orex** [comment]
It looks like, that this is a GULP problem. Try to run GULP with command `gulp < input_r4.51.gulp > g_r4.51.out` and check what is going on there. Probably it gives use some error/hints in output. The script was written 5 years ago. Probably GULP change interface. May be you can download and install old version of the program.

**Comment by redmack** [comment]
I also tried running the command `gulp < input_r4.51.gulp > g_r4.51.out` but same problem. The old version of GULP (4.2) also didn't solve the issue.
In the end, just found a solution. Apparently, it was due to the OS (Ubuntu 20.04 LTS). I just ran the same code in Ubuntu 18.04 and it works fine. Strange!!

**Comment by orex** [comment]
Strange.)))

**Comment by orex** [comment]
Closed due to problem in GULP and 2 weeks of inactivity.
