### ISSUE TITLE
Can't open the program

### ISSUE THREAD

**Issue by quark-wang** [orex/supercell#34]
I have installed the supercell program on windows, but it will crash unexpectedly  when I open the EXE file. After installation on Linux, it will display "input file cannot be opened." Could you help me solve this problem?

**Comment by orex** [comment]
Dear Quark wang,

Let's start from Linux version of the program. This is a "main" version. Please, can you redo a first example (Ca2Al2SiO7) in tutorial (https://orex.github.io/supercell/doc/supercell_tutorial.pdf) step-by-step and compare the results.

Best,
Kirill.

**Comment by quark-wang** [comment]
> Dear Quark wang,
> 
> Let's start from Linux version of the program. This is a "main" version. Please, can you redo a first example (Ca2Al2SiO7) in tutorial (https://orex.github.io/supercell/doc/supercell_tutorial.pdf) step-by-step and compare the results.
> 
> Best,
> Kirill.

Hi Kirill.

It works. Thank you !

Sincerely,
Quark_Wang
