### ISSUE TITLE
issue with large number combination

### ISSUE THREAD

**Issue by SUN123RAY** [orex/supercell#35]
I am using your "Supercell" code to remove the partial occupancy of the attached oxynitride structure. The lattice parameter in .cif is large. So I am considering only 1x1x1 supercell. There are three groups. Group 2 and group 3 is Zr1 and Zr2 site, respectively. Group 1 is O1/N1 with partial occupancies. The problem is that it is showing "Number of combinations for the group is 2254848913647", which is a really big number to treat. Can you please help how to proceed with the "Supercell" code to remove the partial occupancies of O/N?
[EntryWithCollCode50197.cif.zip](https://github.com/orex/supercell/files/5482573/EntryWithCollCode50197.cif.zip)

**Comment by orex** [comment]
Thank you very much for the question. First of all, the number of combinations huge but not impossible. If you have good hardware and some time (may be week or so), you can go through all of them. I can advice you to use electrostatic sampling to get the most relevant structures.
From another side the cif file is already a supercell. Converting the input to primitive cell reduce the number to 735471. Such number of combinations can be processed within a few second. I suggest you to start from this cell.

**Comment by SUN123RAY** [comment]
Thanks for your prompt response. For electrostatic, is it the correct command for 50 structures with lowest Coulomb energy, and the first 20 structures with highest Coulomb energy?
supercell -i xyz.cif -s 1x1x1 -v 2 -m -q -n l50 -n h20 -o xyz_1x1x1

Also is it possible to convert the supercell .cif to primitive cell by this code? If yes, can you please tell me the process? If not, can you suggest me any other code/script to do the same?

**Comment by orex** [comment]
1) Yes. Looks right. Double check, that you specify charges right. You can check it in the supercell output (a table). I also would recommend you to add some random structures for comparison purposes. Please check paper

Cadars, S., Ho Ahn, N., Okhotnikov, K., Shin, J., Vicente, A., Bong Hong, S., & Fernandez, C. (2017). Modeling Short-Range Substitution Order and Disorder in Crystals: Application to the Ga/Si Distribution in a Natrolite Zeolite. Solid State Nuclear Magnetic Resonance. https://doi.org/10.1016/j.ssnmr.2017.04.001
where I discuss in details, an Coulomb energy structure sorting. Probably it can give you some hints for your structure. 
 
2) Supercell code can't do this. It can be implemented in my code quite easily, but perform such structure manipulations with CLI are hellish even for me. I can recommend you an excellent GUI program, called VESTA. An example youtube video is here
https://www.youtube.com/watch?v=PObyydj0GiU

Best,
Kirill.
