### ISSUE TITLE
Bug with Te-metal structure

### ISSUE THREAD

**Issue by sylviancadars** [orex/supercell#37]
Dear Orex  ;o)

I am experiencing 2 distinct problems with the following structure (generated with VESTA) based on Te Metal (P 31 2 1 space group) and mixing with another element (no matter the amount of mixing between the two or the nature of the second element).

test-02.cif

```
#======================================================================
# CRYSTAL DATA
#----------------------------------------------------------------------
data_VESTA_phase_1

_chemical_name_common                  ''
_cell_length_a                         4.456000
_cell_length_b                         4.456000
_cell_length_c                         5.921000
_cell_angle_alpha                      90.000000
_cell_angle_beta                       90.000000
_cell_angle_gamma                      120.000000
_cell_volume                           101.815999
_space_group_name_H-M_alt              'P 31 2 1'
_space_group_IT_number                 152

loop_
_space_group_symop_operation_xyz
   'x, y, z'
   '-y, x-y, z+1/3'
   '-x+y, -x, z+2/3'
   'y, x, -z'
   'x-y, -y, -z+2/3'
   '-x, -x+y, -z+1/3'

loop_
   _atom_site_label
   _atom_site_occupancy
   _atom_site_fract_x
   _atom_site_fract_y
   _atom_site_fract_z
   _atom_site_adp_type
   _atom_site_U_iso_or_equiv
   _atom_site_type_symbol
   Te1         0.5    -0.263600     0.000000     0.333333    Biso  ? Te
   Se1         0.5    -0.263600     0.000000     0.333333    Biso  ? Se

```

In older versions of supercell (a few months old), when I try a dryrun with the -m option : 

`supercell -d -i test-02.cif -s 3x2x1 -m`

the program keeps writing : 
```
ERROR: wrong combination symmetry.
ERROR: wrong combination symmetry.
ERROR: wrong combination symmetry.
...
```

I downloaded that lastest (linux) pre-compiled version and has a different problem : 

`supercell -i test-02.cif -s 3x3x1 -d -m`

```
-------------------------------------------------
The total number of combinations is 20058300(~2.0e+07)
-------------------------------------------------
1674 symmetry operation found for supercell.
Total enumeration time: 0:00:0.128357
Combinations after merge: 0
ERROR: Combination left 20058300 != 0
Write files error.
```

Any idea what is wrong with the structure and/or the program ?
Thank you very much.
All the best.
Sylvian.

**Comment by orex** [comment]
I confirm that the problem is exists. I'm working on it.

**Comment by orex** [comment]
Please check the new version here
https://github.com/orex/supercell/tree/gh-pages/deploy_artifacts/fix_issue37/exe
If OK, then I will merge it to master

**Comment by sylviancadars** [comment]
Dear Orex,
The pre-compiled version now works fine with the previously-problematic Te example.
Thanks for your help and efforts.
All the best.
Sylvian.
