### ISSUE TITLE
Fail to generate supercell model by SUPERCELL

### ISSUE THREAD

**Issue by cugmsn** [orex/supercell#39]
We are trying to generate supercell model of Fe doped alumina-rich spinel (MgO·1.8Al2O3) by using Supercell program, but failed.

- Supercell v2.0 
- the Cif was referred to the MgAlFeO4.cif example. the cif was checked by VESTA and attached here (please remove the ".txt"
[MgAl2O4.cif.txt](https://github.com/orex/supercell/files/6790383/MgAl2O4.cif.txt)).
- command line: 
      supercell.exe -i MgAl2O4.cif -p MgA:p=5 -p AlA:p=3 -p FeA:p=0 -p MgB:p=0 -p AlB:p=14 -p FeB:p=1 -m -o out/spd
- output information comes:
"Command line: E:\xxx\supercell.exe -i MgAl2O4.cif -p MgA:p=5 -p AlA:p=3 -p FeA:p=0 -p MgB:p=0 -p AlB:p=14 -p FeB:p=1 -m -o out/spd
Random SEED: 104959513
Unhandled Exception reached the top of main: MgAl2O4.cif:262:1: Wrong number of values in the loop, application will now exit"

We don't know what does it means. Could you give us some suggestion?

**Comment by orex** [comment]
Hello.

Thank you for the request. This is input file problem, not supercell. Please check the screenshot below.
![Screenshot from 2021-07-09 16-22-56](https://user-images.githubusercontent.com/3882045/125093033-390f7380-e0d2-11eb-9fb9-908bf55b62d9.png)

On the left panel you can see the file you attached, on the right panel the same file from COD (9007271.cif). Please check line 273 last two values. It looks like the value `0.87500.00726` should look like this `0.8750 0.00726` (space added). I can assume that the problem appeared, when you manually changed the occupancy. I suggest you verify the cif file with the publication and check it with tools like EnCiFer. Unfortunately, my program doesn't have a strong "cif verification engine". It relays on validity of the input cif files. Another suggestion is to use a command line interface of `supercell` to change occupancy of different sites. You can get more information about this in the manual and the tutorial.

**Comment by cugmsn** [comment]
Thanks
