### ISSUE TITLE
mixing the element by setting -s 1x1x1

### ISSUE THREAD

**Issue by bbuenim** [orex/supercell#41]
Hi

I have a question.

I would like to mix element by keeping the cell size. just mix the initial element with the other element

EX.) SiO2 

There are 8 Si and 16 O.

8 Si -> 4 Si and 4 Ge So, i prepared the file cif

if I expand cell  (e.g. -s 2x1x1 ) is fine to make cell. but -s 1x1x1 case just give only 1 configuration.

but, There are 8C4= 70 cases

And Although I add charge for each element and consider those charges , it does also give 1 configuration.

Q1. Is it difficult to calculate the intermixing like this case for 1x1x1 in the large unit cell( total number of atoms > 80 , here 32 SI -> 16 Si and 16 Ge)

Thanks

**Comment by orex** [comment]
Hello.

Please:
1) Attach input cif (rename it to txt).
2) Add supercell program output as code block (check markdown syntax).
3) Try to make your request more transparent. Add some details.

A far as I understand now:
1) For such system charge should not be an issue, whenever Ge and Si have the same charge.
2) 16Si + 16Ge is a very simple task for supercell. You can get the result in less than one minute even in your laptop machine.

**Comment by bbuenim** [comment]
Hi

Sorrry for inconvenience.

I attached the input file as txt form(cif file)
[Si2O3.txt](https://github.com/orex/supercell/files/7678534/Si2O3.txt)

Here I would like to change 32 Si into 16 Si and 16 Ge based on charges and get 20 stcutures from the lowest.

and command to run is  "supercell -i Si2O3.cif -s 1x1x1 -m -o 1_50/POSCAR -q -c yes -n l20"

but result is like below:
The initial  was looks good
[image](https://user-images.githubusercontent.com/35595901/145274703-6adb30e2-98da-4181-bba0-672cb518a1d6.png)
But, my scrren stops like below 
![image](https://user-images.githubusercontent.com/35595901/145274597-29da342c-af65-4a38-a9cd-7baa155c21c0.png)

Please confirm this situation.


Thanks for your help.

**Comment by orex** [comment]
Supercell program search for symmetry by labels. So you should have for the same site the same label. Something like this for Si (for Ge also):
```
	Si1	0.5	0.25	0.217318	0.5	Uiso	?	Si
	Si1	0.5	0.282682	0.5	0.75	Uiso	?	Si
	Si1	0.5	0.5	0.25	0.217318	Uiso	?	Si
	Si1	0.5	0.217318	0.5	0.25	Uiso	?	Si
	Si1	0.5	0.5	0.75	0.282682	Uiso	?	Si
        Si12	0.5	0.75	0.217318	0	Uiso	?	Si
```

**Comment by bbuenim** [comment]
>Thanks fot your reply.

But , In my case, 
        labe occ   x         y             z
	Si1	0.5	0.25	0.217318	0.5	Uiso	?	Si
	Si1	0.5	0.282682	0.5	0.75	Uiso	?	Si
	Si1	0.5	0.5	0.25	0.217318	Uiso	?	Si
	Si1	0.5	0.217318	0.5	0.25	Uiso	?	Si
	Si1	0.5	0.5	0.75	0.282682	Uiso	?	Si

these 5 Si have different site as you can x,y,z (fractional coordinate)

Why do you make 5 Si into same label like Si1  from my data ?
so sorry, I don't understand why do you think the 5 Si should have same label.

Could you please tell me why?

Thanks for your help

**Comment by orex** [comment]
Sorry for repeating, but "Supercell program search for symmetry by labels. So you should have for the same site the same label." This 5 Si was only an example. You should check by your self sites and symmetries. Please check the group concept in my paper
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-016-0129-3#Sec5
and the tutorial:
https://orex.github.io/supercell/doc/supercell_tutorial.pdf

**Comment by bbuenim** [comment]
Thanks for your explanations.

I will looked more your links

Thanks
