### ISSUE TITLE
Fixing occupancies

### ISSUE THREAD

**Issue by maa190** [orex/supercell#42]
[Structure.txt](https://github.com/orex/supercell/files/7726446/Structure.txt)
[output.txt](https://github.com/orex/supercell/files/7726471/output.txt)

In order to reduce the time required to convert this structure into a 3x3x3 ordered supercell, I tried using the recommended commands in the tutorial however, the occupancies are not remaining fixed but always changed to 0 and 1.

Input: supercell -i Structure.cif -p "*:fixed"
Output: Attached

**Comment by orex** [comment]
Hello!

The fixed occupancy are stored after corrections. Please check the issue first https://github.com/orex/supercell/issues/27 and try the command

`supercell -i Structure.cif -p "*:fixed" -s 3x3x3`

Feel free to continue the discussion in case of any further questions.

Best,
Kirill

**Comment by orex** [comment]
The issue is resolved.
