### ISSUE TITLE
Problem to initiate the supercell calculation for a Garnet structure

### ISSUE THREAD

**Issue by Jackkan2021** [orex/supercell#45]
Hi Kirill and others

I have used supercell program over the past year and find it every helpful for my reseach. I already tried more than 20 different structures for calculation and all of them were successful. But recently, I have a problem to initiate the supercell calculation for a garnet structure, with a space group of Fm-3m[Li5La3Nb2O12.cif](https://www.dropbox.com/s/fbgbgbtzgna4edk/Li5La3Nb2O12.cif?dl=0) . The garnet cif was first downloaded from ICSD database. Subsequently, I modified slightly for the the oxidation states of atoms in the cif file as follow

**loop_
_atom_type_symbol
_atom_type_oxidation_number
La1 +3
Nb1 +5
O1 -2
Li1 +1
Li2 +1
Li3 +1**

I didn't modify anything for the atomic positions of the atoms.  

**loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_symmetry_multiplicity
_atom_site_Wyckoff_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_U_iso_or_equiv
_atom_site_occupancy
La1 La3+ 24 c 0.125 0 0.25 0.006(1) 1
Nb1 Nb5+ 16 a 0 0 0 0.002(1) 1
O1 O2- 96 h 0.2844(5) 0.1044(6) 0.1996(6) 0.007(3) 1
Li1 Li1+ 24 d 0.25 0.875 0 0.01 0.836
Li2 Li1+ 48 g 0.125 0.6798 0.5702 0.01 0.11
Li3 Li1+ 96 h 0.095 0.6818 0.5778 0.01 0.152**

When I tried to initiate the supercell calculation, I typed "supercell -i Li5La3Nb2O12.cif -d -q -m -n l10 -s 2x2x2"

I got the output message as follow:

Random SEED: 2466491342
CIF file info:
   INFO: Using symmtries from space group.

Initial system: 
   Chemical Formula: La24 Li39.936 Nb16 O96

Supercell system (2x2x2):
   Size a = 25.5898, b 25.5898, c = 25.5898

Current charge balance option is "try"
Total charge oxidation state (cif): -0.064
Total charge cell: -0.064
Charge balancing: yes

ERROR: Group has no unique connection.
Create occupation groups error.

Below is a printscreen of the window.

![image](https://user-images.githubusercontent.com/81632237/154825705-758ae79d-18e7-4407-b3a6-f93276d47ab0.png)

I am not sure what was wrong in the calculation. Would you provide me some advice to solve it? Thank  you very much!

best,
Jack

**Comment by Jackkan2021** [comment]
I found out the solution just ago. It was a tolerence problem. I set it to 1.1 by typing -t 1.1 at the end of the command.

**Comment by orex** [comment]
Hi, Jack!

Awesome, that you had found the solution by yourself. Just want to add some comments:
1) Very similar problem with the same solution is described in Issue https://github.com/orex/supercell/issues/5
2) To solve such kind of problems it is always good to visualize the structure: both input and output. You can use `-p "*:fixed"` command line parameter to get one output structure with partial occupancy.
3) In case of very high displacement, tolerance parameter can't solve the problem. You should edit an input file to place atoms in higher symmetric positions.

You can find more information in the tutorial:
https://orex.github.io/supercell/doc/supercell_tutorial.pdf

**Comment by Hcx99** [comment]
> Hi Kirill and others
> 
> I have used supercell program over the past year and find it every helpful for my reseach. I already tried more than 20 different structures for calculation and all of them were successful. But recently, I have a problem to initiate the supercell calculation for a garnet structure, with a space group of Fm-3m[Li5La3Nb2O12.cif](https://www.dropbox.com/s/fbgbgbtzgna4edk/Li5La3Nb2O12.cif?dl=0) . The garnet cif was first downloaded from ICSD database. Subsequently, I modified slightly for the the oxidation states of atoms in the cif file as follow
> 
> **loop_ _atom_type_symbol _atom_type_oxidation_number La1 +3 Nb1 +5 O1 -2 Li1 +1 Li2 +1 Li3 +1**
> 
> I didn't modify anything for the atomic positions of the atoms.
> 
> **loop_ _atom_site_label _atom_site_type_symbol _atom_site_symmetry_multiplicity _atom_site_Wyckoff_symbol _atom_site_fract_x _atom_site_fract_y _atom_site_fract_z _atom_site_U_iso_or_equiv _atom_site_occupancy La1 La3+ 24 c 0.125 0 0.25 0.006(1) 1 Nb1 Nb5+ 16 a 0 0 0 0.002(1) 1 O1 O2- 96 h 0.2844(5) 0.1044(6) 0.1996(6) 0.007(3) 1 Li1 Li1+ 24 d 0.25 0.875 0 0.01 0.836 Li2 Li1+ 48 g 0.125 0.6798 0.5702 0.01 0.11 Li3 Li1+ 96 h 0.095 0.6818 0.5778 0.01 0.152**
> 
> When I tried to initiate the supercell calculation, I typed "supercell -i Li5La3Nb2O12.cif -d -q -m -n l10 -s 2x2x2"
> 
> I got the output message as follow:
> 
> Random SEED: 2466491342 CIF file info: INFO: Using symmtries from space group.
> 
> Initial system: Chemical Formula: La24 Li39.936 Nb16 O96
> 
> Supercell system (2x2x2): Size a = 25.5898, b 25.5898, c = 25.5898
> 
> Current charge balance option is "try" Total charge oxidation state (cif): -0.064 Total charge cell: -0.064 Charge balancing: yes
> 
> ERROR: Group has no unique connection. Create occupation groups error.
> 
> Below is a printscreen of the window.
> 
> ![image](https://user-images.githubusercontent.com/81632237/154825705-758ae79d-18e7-4407-b3a6-f93276d47ab0.png)
> 
> I am not sure what was wrong in the calculation. Would you provide me some advice to solve it? Thank you very much!
> 
> best, Jack

Hello! The structure I am making is also garnet type, which is also occupied by Li fraction. I would like to ask you how to operate the doping element. Thank you very much!

**Comment by orex** [comment]
Following the suggestions in the comment above https://github.com/orex/supercell/issues/45#issuecomment-1046210746 and "Supercell program good practices" in the tutorial https://orex.github.io/supercell/external/doc/supercell_tutorial.pdf, please extend your problem description with detailed visualized structure, site distances and surrounding table.
