### ISSUE TITLE
Choice of atoms when maintaining charge

### ISSUE THREAD

**Issue by maa190** [orex/supercell#46]
Hello 

I am currently doping a disordered structure and then using the program to order it into a supercell. I would like to understand what is logic that the program chooses when it tries to maintain the charge neutral. 

In other words, if my dopant has a charge of 3+ and is substituting a element with a different charge say 4+, the program will try to remove some elements in order to compensate for the charge. How does it make the choice?

Thank you!

**Comment by orex** [comment]
Hello

Please check the original supercell paper.
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-016-0129-3 

The algorithm is discussed in details in "Stage III: Occupancy correction" paragraph.

Best,
Kirill.
