### ISSUE TITLE
The Coulomb energy is zero

### ISSUE THREAD

**Issue by Hcx99** [orex/supercell#47]
Hello!
llzoyb_out/llzo_il00000000_w4.cif	0.000 eV
llzoyb_out/llzo_il00000001_w4.cif	0.000 eV
llzoyb_out/llzo_il00000002_w4.cif	0.000 eV
llzoyb_out/llzo_il00000003_w4.cif	0.000 eV
llzoyb_out/llzo_il00000004_w4.cif	0.000 eV

Here is the log file

Minimal distance between atoms of two distinct groups: 0.652594 A.
-------------------------------------------------
The total number of combinations is 52097760(~5.2e+07)
-------------------------------------------------
4 symmetry operation found for supercell.
Symmetries operation assigned to groups.
Start Coulomb matrix (106x106) calculation.
Coulomb matrix calculation finished.
Output files was deleted successfully
Finished 68.2%. Stored 9413720 configurations. Left 14442880          
Total enumeration time: 0:00:1.46505
Combinations after merge: 13024440

CIF
_chemical_name_common                  'Heptalithium trilanthanum dizirconium '
_cell_length_a                         11.261361
_cell_length_b                         11.261361
_cell_length_c                         11.261361
_cell_angle_alpha                      109.471222
_cell_angle_beta                       109.471222
_cell_angle_gamma                      109.471222
_cell_volume                           1099.387373
_space_group_name_H-M_alt              'P 1'
_space_group_IT_number                 1

loop_
_space_group_symop_operation_xyz
   'x, y, z'

loop_
   _atom_site_label
   _atom_site_occupancy
   _atom_site_fract_x
   _atom_site_fract_y
   _atom_site_fract_z
   _atom_site_adp_type
   _atom_site_U_iso_or_equiv
   _atom_site_type_symbol
   Li1        0.5640  0.625000     0.375000     0.250000    Uiso  0.026000 Li
   Li1        0.5640  0.375000     0.625000     0.750000    Uiso  0.026000 Li
   Li1        0.5640  0.875000     0.125000     0.750000    Uiso  0.026000 Li
   Li1        0.5640  0.125000     0.875000     0.250000    Uiso  0.026000 Li
   Li1        0.5640  0.250000     0.625000     0.375000    Uiso  0.026000 Li
   Li1        0.5640  0.750000     0.375000     0.625000    Uiso  0.026000 Li
   Li1        0.5640  0.750000     0.875000     0.125000    Uiso  0.026000 Li
   Li1        0.5640  0.250000     0.125000     0.875000    Uiso  0.026

**Comment by orex** [comment]
You should specify charges to get Coulomb energy. Please check the docs.
https://orex.github.io/supercell/docs/

**Comment by Hcx99** [comment]
I used your method and coulomb energy is available!  But the log output ended at 73.2%.  
4 symmetry operation found for supercell.
Symmetries operation assigned to groups.
Start Coulomb matrix (106x106) calculation.
Coulomb matrix calculation finished.
Output files was deleted successfully
Finished 73.2%. Stored 9861730 configurations. Left 12650840          
Total enumeration time: 0:00:1.36075
Combinations after merge: 13024440

**Comment by orex** [comment]
The program was finished successfully.
