### ISSUE TITLE
Antisite defect calculation. 

### ISSUE THREAD

**Issue by Anny-tech** [orex/supercell#48]
Hi I had been trying to create structures with antisite defects in a simple Bi2Te3 system but to no avail. The -p property is not giving more than 1 structure, despite mentioning the A and B site occupancies of Bi atoms. Would it be possible to provide an example for such a system? I am attaching the .cif file I am using for the system. (Had to convert to a .txt extension for uploading)
[Bi2Te3_prim_pristine_1.cif.txt](https://github.com/orex/supercell/files/8794799/Bi2Te3_prim_pristine_1.cif.txt)

**Comment by orex** [comment]
Hi!
All of your sites have 100% occupancy. `supercell` can't produce derivative structures. Please check tutorial for an examples.
https://orex.github.io/supercell/docs/tutorial/
