### ISSUE TITLE
ERROR: Group has no unique connection.

### ISSUE THREAD

**Issue by hlyang1992** [orex/supercell#5]
There is a error when deal with file below which is generated by findit.
[Cu2Se-41141.cif.zip](https://github.com/orex/supercell/files/675001/Cu2Se-41141.cif.zip)

**Comment by orex** [comment]
It seems to be, that the file in zip archive is corrupted (not valid cif). Can you check it?

**Comment by hlyang1992** [comment]
I can read the file using vesta. Then export to cif in vesta.  I still get this error with the new file exported by vesta. Could you please tell me how to check it ?

**Comment by orex** [comment]
Just download the zip, you attached, unpack the file and check, that you can still open it with VESTA

**Comment by hlyang1992** [comment]
I am very sorry for the bad file. I don't know why the file is broken. I upload the new file to google drive.[good cif](https://drive.google.com/file/d/0B7DapXLbWsRKY3ZmSXlxdUZ4TjQ/view?usp=sharing)

**Comment by orex** [comment]
Now, it is good. I will return to you tomorrow.

**Comment by orex** [comment]
Cu1 and Cu2 sites are located close to each other (see picture).

![cu2se-41141](https://cloud.githubusercontent.com/assets/3882045/21516549/547fd98a-ccea-11e6-99f4-b6814b8fe551.png)

Therefore, they can not be occupied simultaneously. Supercell program is trying to combine them to one group, but it fails, because the default value of distance within group parameter ( --tolerance) is low for the structure. To solve the problem, I can recommend you to change the default value of the parameter to 1.1.
`supercell -i Cu2Se-41141.cif -t 1.1`

For more information, please refer to http://jcheminf.springeropen.com/articles/10.1186/s13321-016-0129-3#Sec5
and to PZT example in tutorial
https://orex.github.io/supercell/doc/supercell_tutorial.pdf
PZT: https://github.com/orex/supercell/tree/master/data/examples/PZT

P.S. Be careful, it is necessary to perform geometry optimization procedure for such type of compounds to achieve reliable results.

**Comment by hlyang1992** [comment]
Thank you for your help..

**Comment by joellohyy** [comment]
Hi,
when I tried to run the supercell.exe on In2O3 2310009.cif (as shown below), ./supercell -d -i 2310009.cif, it outputs

Current charge balance option is "try"
Total charge oxidation state (cif):  nan
Total charge cell:   0
Charge balancing:   yes
----------------------------------------------------------------
| Atom Label	| 	charge  	| mult	| occup x mult
| 		| Ox. state	| Used	| (cif)	|		 
----------------------------------------------------------------
|  In1		|  nan		|  0	|  8	|  8
|  In2		|  nan		|  0	|  24	|  24
|  O1		|  nan		|  0	|  48	|  48
----------------------------------------------------------------

Chemical formula of the supercell: In32 O48
Total charge of supercell: 0

If I manually set the charge 
./supercell -d -p "In1:c=+3" -p "In2:c=+3" -p "O1:c=-2" -i 2310009.cif
I still get nan in the ox.state table. 
----------------------------------------------------------------
| Atom Label	| 	charge  	| mult	| occup x mult
| 		| Ox. state	| Used	| (cif)	|		 
----------------------------------------------------------------
|  In1		|  nan		|  3	|  8	|  8
|  In2		|  nan		|  3	|  24	|  24
|  O1		|  nan		|  -2	|  48	|  48
----------------------------------------------------------------

I've managed to run the examples in the tutorials without any problems, the Ox.state column would show the correct values. 

I don't see a problem in the cif. file below. How do I set the Ox charge properly?

```
#------------------------------------------------------------------------------
#$Date: 2016-02-21 11:56:54 +0200 (Sun, 21 Feb 2016) $
#$Revision: 176809 $
#$URL: svn://www.crystallography.net/cod/cif/2/31/00/2310009.cif $
#------------------------------------------------------------------------------
#
# This file is available in the Crystallography Open Database (COD),
# http://www.crystallography.net/. The original data for this entry
# were provided by IUCr Journals, http://journals.iucr.org/.
#
# The file may be used within the scientific community so long as
# proper attribution is given to the journal article from which the
# data were obtained.
#
data_2310009
loop_
_publ_author_name
'Marezio, M.'
_publ_section_title
;
 Refinement of the crystal structure of In2O3 at two wavelengths
;
_journal_issue                   6
_journal_name_full               'Acta Crystallographica'
_journal_page_first              723
_journal_page_last               728
_journal_volume                  66
_journal_year                    1966
_chemical_formula_structural     'In2 O3'
_chemical_formula_sum            'In2 O3'
_chemical_name_systematic        'Indium Oxide'
_space_group_IT_number           206
_symmetry_Int_Tables_number      206
_symmetry_space_group_name_Hall  '-I 2b 2c 3'
_symmetry_space_group_name_H-M   'I a -3'
_cell_angle_alpha                90.
_cell_angle_beta                 90.
_cell_angle_gamma                90.
_cell_formula_units_Z            16
_cell_length_a                   10.117(1)
_cell_length_b                   10.117(1)
_cell_length_c                   10.117(1)
_cell_volume                     1035.51(18)
_cod_data_source_file            In2O3_Ia-3_DC235.cif
_cod_data_source_block           chateigner_1508504
_cod_original_cell_volume        1035.51
_cod_database_code               2310009
loop_
_symmetry_equiv_pos_site_id
_symmetry_equiv_pos_as_xyz
1 '-z, x, y+1/2'
2 'z, x+1/2, -y'
3 'z+1/2, -x, y'
4 '-z, -x, -y'
5 'y+1/2, -z, x'
6 '-y, z, x+1/2'
7 'y, z+1/2, -x'
8 '-y, -z, -x'
9 'x, y+1/2, -z'
10 'x+1/2, -y, z'
11 '-x, y, z+1/2'
12 '-x, -y, -z'
13 'z, -x, -y+1/2'
14 '-z, -x+1/2, y'
15 '-z+1/2, x, -y'
16 'z, x, y'
17 '-y+1/2, z, -x'
18 'y, -z, -x+1/2'
19 '-y, -z+1/2, x'
20 'y, z, x'
21 '-x, -y+1/2, z'
22 '-x+1/2, y, -z'
23 'x, -y, -z+1/2'
24 'x, y, z'
25 '-z+1/2, x+1/2, y'
26 'z+1/2, x, -y+1/2'
27 'z, -x+1/2, y+1/2'
28 '-z+1/2, -x+1/2, -y+1/2'
29 'y, -z+1/2, x+1/2'
30 '-y+1/2, z+1/2, x'
31 'y+1/2, z, -x+1/2'
32 '-y+1/2, -z+1/2, -x+1/2'
33 'x+1/2, y, -z+1/2'
34 'x, -y+1/2, z+1/2'
35 '-x+1/2, y+1/2, z'
36 '-x+1/2, -y+1/2, -z+1/2'
37 'z+1/2, -x+1/2, -y'
38 '-z+1/2, -x, y+1/2'
39 '-z, x+1/2, -y+1/2'
40 'z+1/2, x+1/2, y+1/2'
41 '-y, z+1/2, -x+1/2'
42 'y+1/2, -z+1/2, -x'
43 '-y+1/2, -z, x+1/2'
44 'y+1/2, z+1/2, x+1/2'
45 '-x+1/2, -y, z+1/2'
46 '-x, y+1/2, -z+1/2'
47 'x+1/2, -y+1/2, -z'
48 'x+1/2, y+1/2, z+1/2'
loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_symmetry_multiplicity
_atom_site_Wyckoff_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_occupancy
_atom_site_attached_hydrogens
_atom_site_B_iso_or_equiv
In1 In3+ 8 b 0.25 0.25 0.25 1. 0 0.46
In2 In3+ 24 d 0.4663(1) 0 0.25 1. 0 0.41
O1 O2- 48 e 0.3912(12) 0.1558(11) 0.3796(13) 1. 0 0.45
loop_
_atom_type_symbol
_atom_type_oxidation_number
In3+ +3
O2- -2

```
