### ISSUE TITLE
unexpected output when there are only two atoms in the unit cell

### ISSUE THREAD

**Issue by Satinelamp** [orex/supercell#51]
I create a cif file that only contains two atoms:
```
Zn15-T1      0.5   0   0   0.5
Cd15-T1     0.5   0  0   0.5
```
I expect `supercell` would output 2 configurations, which contain one type of atom in the unit cell, respectively, but  there is only one output configuration, here is the output:

```
Chemical formula of the supercell: Cd1 Zn0
Total charge of supercell: 0

----------------------------------------------------
 Identification of groups of crystallographic sites
----------------------------------------------------

 Group 1 (1 atomic positions in supercell):
   Site #1: Zn15-T1 (occ. 0.5) -> FIXED with occupancy 0.000.
   Site #2: Cd15-T1 (occ. 0.5) -> FIXED with occupancy 1.000.

Minimal distance between atoms of two distinct groups: -1 A.

-------------------------------------------------
The total number of combinations is 1
```
Here are the detailed log and cif files I use.
[cif.zip](https://github.com/orex/supercell/files/9338420/cif.zip)

[output.txt](https://github.com/orex/supercell/files/9338425/output.txt)

**Comment by orex** [comment]
Supercell is not working in such way. The output configurations have fixed composition. Composition you can vary by yourself, using, for example, `-p` parameter. See tutorial
https://orex.github.io/supercell/docs/tutorial/
and supercell paper 
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-016-0129-3

**Comment by orex** [comment]
Let's say that this is a random choice.
