### ISSUE TITLE
The program get stuck when dealing with surface model

### ISSUE THREAD

**Issue by Satinelamp** [orex/supercell#52]
I create a surface model, and tried to use `supercell` to make disorder replacement, but the prgrom got stuck after I execute 
`supercell -i CdS-110.cif -v 2 -p "*T2:fixed" -p "*T3:fixed" -p "*T4:fixed" -p "*T5:fixed" -p "*T6:fixed" -n
r1 -o step1`

![Snipaste_2022-08-16_00-23-41](https://user-images.githubusercontent.com/62006565/184674862-53c528d2-42bd-45ae-a8b0-fc99550eb63b.png)

![image](https://user-images.githubusercontent.com/62006565/184675174-bf817967-dfb4-4672-b466-65f6294688a2.png)

Here are the log file and cif file I use:
[surface.zip](https://github.com/orex/supercell/files/9338483/surface.zip)

**Comment by orex** [comment]
I confirm that the problem exists, but I have a strong feeling that the structure you trying to process can't give you the result you expect. Please check paper (grouping conception) and tutorial to obtain extra information about the `supercell` input.

**Comment by Satinelamp** [comment]
My idea is to build a supcell of ZnS which include 108 atoms, and assign the fraction occupation number for the Zn sites(Zn=0.5,Cd=0.5) by hand, and then use `supercell` program to help distribute the `Zn` and `Cd` elements randomly, so I could get a final strucutre.
Is this gonna work?

**Comment by orex** [comment]
Certainly, yes. Please check deeply examples in tutorial.
