### ISSUE TITLE
Partial occupancy groups get fixed by themselves

### ISSUE THREAD

**Issue by gagarofalo** [orex/supercell#58]
Hi,

I'm trying to generate some disordered cells, but with all the .cif files I use the occupancy gets fixed.
I tried to do some tests with different percentages and it seems it chooses 1 for the atom with the highest percentage, even if it's 51. This is one of the .cif files, with just one partial occupied site: 

_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   5.60256400
_cell_length_b   5.60256400
_cell_length_c   5.60256400
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Fe3Si
_chemical_formula_sum   'Fe12 Si4'
_cell_volume   175.85733158
_cell_formula_units_Z   4
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Fe  Fe0  1  0.25000000  0.25000000  0.75000000  0.5
  Si  Si0  1  0.25000000  0.25000000  0.75000000  0.5
  Fe  Fe1  1  0.00000000  0.00000000  0.00000000  1
  Fe  Fe2  1  0.25000000  0.75000000  0.75000000  1
  Fe  Fe3  1  0.25000000  0.75000000  0.25000000  1
  Fe  Fe4  1  0.00000000  0.50000000  0.50000000  1
  Fe  Fe5  1  0.25000000  0.25000000  0.25000000  1
  Fe  Fe6  1  0.75000000  0.25000000  0.25000000  1
  Fe  Fe7  1  0.50000000  0.00000000  0.50000000  1
  Fe  Fe8  1  0.75000000  0.75000000  0.25000000  1
  Fe  Fe9  1  0.75000000  0.75000000  0.75000000  1
  Fe  Fe10  1  0.50000000  0.50000000  0.00000000  1
  Fe  Fe11  1  0.75000000  0.25000000  0.75000000  1
  Si  Si12  1  0.50000000  0.00000000  0.00000000  1
  Si  Si13  1  0.50000000  0.50000000  0.50000000  1
  Si  Si14  1  0.00000000  0.00000000  0.50000000  1
  Si  Si15  1  0.00000000  0.50000000  0.00000000  1

and here is the output I got after executing `supercell -d -i <input>.cif -m`:

![Issue_supercell](https://user-images.githubusercontent.com/110853043/202482542-ea96298f-c21e-4754-9d64-794554f55c81.png)

The other groups are fixed, as they should be.
What am I doing wrong?

**Comment by orex** [comment]
In the example you wrote, there is only one site for the disordered atom. So, it is occupied either by 1 Fe or 1 Si atom. Please increase the cell size to get the result. For example,
```
supercell -d -i <input>.cif -m -s 2x2x2
```

**Comment by gagarofalo** [comment]
But in the Ca2Al2SiO7 example the disordered site is distributed even in the 1x1x1 run.
I would like to avoid increasing the cell size because, in the end, I'd like to do just one 1x1x1 big cluster (100s of atoms big) randomly assigning the site species. Is that possible?

**Comment by orex** [comment]
Again. You have ONE site with multiplicity 1 in you cell. When you have only physical 1 place where you can put your atom, it is not possible to distribute several atoms around one site (see output).
```
...
Group 1 (1 atomic position in supercell):
...
``` 
For  Ca2Al2SiO7 example:

```
....
 Group 2 (4 atomic positions in supercell):
  * Site #1: AlT2 (occ. 0.5) -> distributed over 2 positions out of 4 (actual occ.: 0.500).
  * Site #2: SiT2 (occ. 0.5) -> distributed over 2 positions out of 4 (actual occ.: 0.500).
  Number of combinations for the group is 6
...
```

**Comment by gagarofalo** [comment]
Ok thanks I see.
