### ISSUE TITLE
Equivalent postion tolerance

### ISSUE THREAD

**Issue by ColinHF** [orex/supercell#59]
How does the tolerance option work becuase I think it's not what I initially thought it did. For my system, I have a cif file that has no symmetry operations. But that's only because the coordinates of the atoms have many decimal points. If you rounded to the third decimal place, that would start to be symmetry again. I work with AIMD, so atoms move around. So a few hundredths of an angstrom difference is the same from a chemistry point of view. Is there an option within supercell that can force equivalent positions based on a tolerance? Thanks for the help

**Comment by orex** [comment]
Yes. The tolerance option is `-t` the default value is 0.75 Angstrom which should me more than enough for your case.

**Comment by ColinHF** [comment]
When I try to introduce one oxygen vacancy, it says there are no equivalent crystal structures. But just visually looking at the cif file. Atoms 153 and 93 appear to be equivalent, so there should be equivalent crystal structures with one vacancy.

**Comment by ColinHF** [comment]
When I try to introduce one oxygen vacancy, it says there are no equivalent crystal structures. But just visually looking at the cif file. Atoms 153 and 93 appear to be equivalent, so there should be equivalent crystal structures with one vacancy.
[2x2x2-CaMnFe2O3_i000_w64.txt](https://github.com/orex/supercell/files/10762061/2x2x2-CaMnFe2O3_i000_w64.txt)

**Comment by orex** [comment]
Please write in details: a goal, input file, program options and picture of structure.

**Comment by ColinHF** [comment]
Goal: I would like to have multiple crystal structures with one oxygen vacancy site. Then I can run energy calculations to see how it changes with respect the distance of two iron atoms
Input File: 
[2x2x2-CaMnFe2O3_i000_w64.txt](https://github.com/orex/supercell/files/10762085/2x2x2-CaMnFe2O3_i000_w64.txt) (Its actually a cif but github wont let me upload it)
Program: supercell -d -i 2x2x2-CaMnFe2O3_i000_w64.cif -s 1x1x1 -p "O:p=95"
Response: 
Total combinations: 96
Toal combinations after merge: 96

Problem: This should be less than 96 since atoms 153 and 93 and the same. Its hard to see in the picture, but if you open the input file in VESTA you'll see that this two oxygen should be the same
![Screen Shot 2023-02-16 at 7 34 09 PM](https://user-images.githubusercontent.com/125614873/219519478-c2942618-f849-4bb5-b3d4-079e75b65c2b.png)

**Comment by orex** [comment]
If two atoms are the same, that does not mean that the cell has symmetry. Check the structure with another tool for crystallographic symmetry and attach the result.
