### ISSUE TITLE
Wrong Charge Balance input in LiMnNb Rocksalt

### ISSUE THREAD

**Issue by HuuTDo** [orex/supercell#62]
Dear Supercell Developers:

I downloaded and run Supercell software to generate initial configurations for Nb-Mn-based disordered rocksalt.
If I don’t include the charge-balance, it runs fine. 
However, as you said in your manual, there are too many configurations to be created.
(I attached link for Input -- LiMnO.cif).  
https://drive.google.com/file/d/1Hud5cpTBYQ5zs47c04yeReiUeGj26IVQ/view?usp=drive_link

**~/supercell -i LiMnO.cif -s 2x2x2  -p "Nb1:p=5” -p "Mn1:p=6" -p "Li1:p=21" -m -o ~/LiMnNb-RS**

However, my run is getting an error (**called  Random SEED: 2673013821
Wrong Charge Balance input**) when I include charge-balance task in running script.
(Here, Li +1, Mn +3 and Nb +5). I am not sure I understand correctly your guide in you manual.

**~/supercell -i LiMnO.cif -s 2x2x2 -c --charge-balance=balance-type -n l100 -q  -p "Nb1:p=5” -p "Mn1:p=6" -p "Li1:p=21" -m -o ~/LiMnNb-RS**

If you know what error is it, could you please tell me the reason?

I really appreciate for your time and attention!

**Comment by orex** [comment]
`--charge-balance=balance-type` is a wrong type of input. Please check manual for possible allowed keys. 
https://orex.github.io/supercell/docs/manual/
