### ISSUE TITLE
Wrong atomic site multiplicity

### ISSUE THREAD

**Issue by Romaker** [orex/supercell#64]
Well, the problem is simple, supercell defines a 48f (x, 1/8 1/8) site as 96g (x, y, y). The space group is 227 (Fd-3m, O2).
Screenshot of VESTA and Supercell is attached. Supercell version - 2.1 (the latest at the moment).
![Example](https://github.com/orex/supercell/assets/161709009/04323a65-678c-44bb-86a8-452847761965)

**Comment by orex** [comment]
Well, solution should be also simple. Excerpt from tutorial (https://orex.github.io/supercell/docs/tutorial/) "Supercell program good practices":
1) If you think, that VESTA read file properly, convert the structure to P1 (conventional cell) and use it as input for *supercell*. 
2) If 1 is wrong, please attach to the issue both files. If good, check the input file group. Probably the spacegroup record is incorrect or uncompleted.

**Comment by orex** [comment]
The issue is closed due to inactivity.
