### ISSUE TITLE
how to use supercell in layered structure

### ISSUE THREAD

**Issue by BigBMonster** [orex/supercell#65]
Dear Orex

Suppose there are three layers of transition metals in some layered structure, and I make atomic replacements for these three layers, but the output contains: the first layer is arranged in A way, the second layer is arranged in B way, and the third layer is arranged in C way. What I want is for each result to be arranged in an A-A-A fashion. Can you tell me how to use "supercell" to achieve the action I want, looking forward to your reply

**Comment by orex** [comment]
Hello BigBMonster!

If I understand you task correctly you just need to take a structure with one layer, create all permutation in A way and create a supercell with triple size. In this case you will get the A-A-A fashion.

Best,
Kirill.

**Comment by orex** [comment]
If you have layers arranged in the same way it means that the structure has
translation symmetry. If you need only the structures with the property,
you need to generate all possible combination on one layer and expand it to
3 same one.
