### ISSUE TITLE
Build fails with the recent Open Babel 2.4.1

### ISSUE THREAD

**Issue by blokhin** [orex/supercell#9]
```
root@debian-16gb ~/supercell/build # make
[  9%] Building CXX object src/sc_cli/CMakeFiles/supercell.dir/__/core/d2o_main_class.cpp.o
/root/supercell/src/core/d2o_main_class.cpp:16:32: fatal error: openbabel/elements.h: No such file or directory
 #include <openbabel/elements.h>
                                ^
compilation terminated.
```
Isn't this related to the following?

> All operations on the structure of the compound ... are done with a customized version of the OpenBabel  [39] library, which was modified by KO to handle partial occupancy in CIF file reading and writing operations. This version of OpenBabel is available from the official Website [40], and the corresponding changes will be merged to the official OpenBabel repository  [41]

**Comment by orex** [comment]
Dear Evgeny,
Thank you for reporting the issue. Recently, OpenBabel changed API to obtain an information from Periodic Table of Elements. Therefore, I've change recently my code to fix the compilation. See
https://github.com/orex/supercell/commit/48976d8216a43a9abe50b74cd928d5dd6ec3b82a

If you would like to use my program, you can
1) Download compiled version from site http://orex.github.io/supercell/
2) Install the newest (master) version of OpenBabel
3) Apply fix to supercell code, which revert changes in the commit above.

Best regards,
Kirill.

**Comment by blokhin** [comment]
Dear Kirill,

thanks a lot for your kind feedback! I've selected the most straightforward option (1).
Hopefully, OpenBabel team will manage to prepare release soon.

**Comment by orex** [comment]
Fixed in https://github.com/orex/supercell/commit/4a32fa840dcccb09b51b05ca92dbd83a306d7eca
